name: Release Service
on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - 1.*

jobs:
  uat:
    uses: MyJetWallet/DevOps/.github/workflows/rust_build.yml@master
    if: startsWith(github.event.ref, 'refs/tags/1')
    with:
      repository_name: ${{ github.event.repository.name }}
      repository_type: ${{ github.event.repository.private }}
      release_version: ${GITHUB_REF#refs/tags/}
    secrets: 
      ST_DOCKER_USER: ${{ secrets.ST_DOCKER_USER }}
      ST_DOCKER_PASSWORD: ${{ secrets.ST_DOCKER_PASSWORD }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      UAT_GIT_TOKEN: ${{ secrets.UAT_GIT_TOKEN }}
  test:
    uses: MyJetWallet/DevOps/.github/workflows/rust_build_test.yml@master
    if: github.ref == 'refs/heads/master'
